// Auto-generated post manifest - DO NOT EDIT MANUALLY
// This file is generated by scripts/generate-posts.js
export const postManifest = [
  {
    "slug": "10-ways-coaching-therapy-sucks",
    "title": "10 Ways Coaching and Therapy Sucks for AuDHD Adults, and What We Need to Do About It",
    "date": "2025-07-04",
    "excerpt": "You, the AuDHD adult, you’ve felt this. This slow, soul-deep burn when the very systems meant to support us simply… don't. It’s not your fault, never your fault, that the frameworks aren’t built for your brain. It’s what needs to shift. We need to talk about it openly.",
    "author": "Francois Dab",
    "tags": [
      "AuDHD",
      "coaching",
      "therapy"
    ],
    "readingTime": "5 min read"
  },
  {
    "slug": "working-through-burnout",
    "title": "Autistic Burnout: Why Your \"Rest\" Isn't Working (And What To Do About It)",
    "date": "2025-06-23",
    "excerpt": "There's so many wrong ways to go about it, and they will just make things worse",
    "author": "Francois Dab",
    "tags": [
      "AuDHD",
      "coaching",
      "burnout"
    ],
    "readingTime": "5 min read"
  },
  {
    "slug": "mindset-vs-wiring",
    "title": "Mindset vs Wiring",
    "date": "2025-06-18",
    "excerpt": "There's a huge difference between MINDSET and WIRING. We need to understand it.",
    "author": "Francois Dab",
    "tags": [
      "AuDHD",
      "coaching",
      "neurodiversity"
    ],
    "readingTime": "6 min read"
  }
];