#!/usr/bin/env node

import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import matter from 'gray-matter';
import readingTime from 'reading-time';

async function generatePostManifest() {
  try {
    const postsDir = join(process.cwd(), 'app/posts');
    const files = await readdir(postsDir);
    const mdxFiles = files.filter(file => file.endsWith('.mdx'));
    
    const posts = await Promise.all(
      mdxFiles.map(async (file) => {
        const filePath = join(postsDir, file);
        const fileContent = await readFile(filePath, 'utf-8');
        const { data, content } = matter(fileContent);
        
        // Extract slug from filename
        const slug = file.replace('.mdx', '');
        
        // Calculate reading time
        const stats = readingTime(content);
        
        return {
          slug,
          title: data.title,
          date: data.date,
          excerpt: data.excerpt,
          author: data.author,
          tags: data.tags || [],
          readingTime: data.readingTime || stats.text,
          ...(data.image && { image: data.image })
        };
      })
    );
    
    // Sort by date (newest first)
    return posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  } catch (error) {
    console.error('Error generating post manifest:', error);
    return [];
  }
}

async function generateAndWriteManifest() {
  try {
    console.log('Generating post manifest...');
    const manifest = await generatePostManifest();
    
    const manifestContent = `// Auto-generated post manifest - DO NOT EDIT MANUALLY
// This file is generated by scripts/generate-posts.js
export const postManifest = ${JSON.stringify(manifest, null, 2)};`;

    const outputPath = join(process.cwd(), 'app/posts/index.ts');
    await writeFile(outputPath, manifestContent);
    
    console.log(`✅ Generated manifest with ${manifest.length} posts`);
    console.log('Posts:', manifest.map(p => `- ${p.title} (${p.date})`).join('\n'));
  } catch (error) {
    console.error('❌ Error generating post manifest:', error);
    process.exit(1);
  }
}

generateAndWriteManifest();